### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [SeokyeongKim/PY202309#3]
### 없는 파일
- practice/week5/turtle.ipynb
	- 위 파일 이름이나 위치를 다시 확인하세요. 해당 소스 파일 채점이 수행되지 않습니다.

### 기능/코드 대비 주석이 부족합니다. 주석을 추가하거나 쪼개세요.
- Insufficient comments in project/week8/search_engine

**Comment by SeokyeongKim** [comment]
안녕하세요 교수님
IoT인공지능융합전공 김석영입니다.
말씀해주신 부분 수정하여 다시 반영하였습니다. (practice/week5/turtle.ipynb)

다만 Insufficient comments in project/week8/search_engine의 경우 주석이 부족하다고 하셨는데, 현재 아래와 같이  search_engine.ipynb에서 line당 하나씩 주석이 포함되어 있습니다. 설명이 부족한 부분 말씀해주시면 다시 수정하여 채워넣도록 하겠습니다. 
감사합니다.


![스크린샷 2023-11-01 오전 9 27 18](https://github.com/SeokyeongKim/PY202309/assets/91733447/4020b358-bfbf-45d4-b68c-f501f3de9e34)

**Comment by MisooKim2** [comment]
안녕하세요.
평가코드상 문제가 있었던 것 같습니다.
주석 매우 잘 다셔서 더 안적으셔도 될 것 같습니다.
이 이슈는 닫아주세요.
